services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    profiles: ["tunnel"]
    command: tunnel run
    environment:
      TUNNEL_TOKEN_FILE: /run/secrets/tunnel_token
    restart: unless-stopped
    secrets:
      - tunnel_token
    depends_on:
      - ktor-backend
      - minio

  postgres-db:
    image: postgres:17
    container_name: inventory-db
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    secrets:
      - db_pass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: inventory-img-db
    read_only: true
    tmpfs:
      - /tmp
      - /root/.minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_pass
    command: server /data --console-address ":9001"
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data
    secrets:
      - minio_pass

  ktor-backend:
    container_name: inventory-be
    build: .
    read_only: true
    tmpfs:
      - /tmp:exec,mode=1777
    env_file:
      - .env
    ports:
      - "127.0.0.1:8081:8080"
    secrets:
      - db_pass
      - minio_pass
      - auth_pepper
      - jwt_secret
    depends_on:
      postgres-db:
        condition: service_healthy
      minio:
        condition: service_started

volumes:
  pg_data:
  minio_data:

secrets:
  db_pass:
    file: ./secrets/db_pass.txt
  minio_pass:
    file: ./secrets/minio_pass.txt
  tunnel_token:
    file: ./secrets/tunnel_token.txt
  auth_pepper:
    file: ./secrets/auth_pepper.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
