ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [ com.kevinfreyap.MainKt.module ]
  }
}

auth {
    pepper = ${?AUTH_PEPPER_SECRET}
}

jwt {
    secret = ${?JWT_SECRET}

    issuer = "http://localhost:8081"
    issuer = ${?JWT_ISSUER}

    audience = "inventory-app"
    audience = ${?JWT_AUDIENCE}
}