ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [ com.kevinfreyap.MainKt.module ]
  }
}

database {
    url = ${?POSTGRES_JDBC_URL}
    user = ${?POSTGRES_USER}
}

minio {
    url = ${?MINIO_URL}
    publicUrl = ${?MINIO_PUBLIC_URL}
    accessKey = ${?MINIO_ROOT_USER}
}

jwt {
    issuer = "http://localhost:8081"
    issuer = ${?JWT_ISSUER}

    audience = "inventory-app"
    audience = ${?JWT_AUDIENCE}
}